apiVersion: v1
kind: Service
metadata:
  name: gitlab-bulks-svc
  namespace: $NAMESPACE
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  type: ClusterIP
  selector:
    app: gitlab-bulks
